name: ' Deploy Reference Documentation'

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write
  pages: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  DeployALDoc:
    runs-on: [ windows-latest ]
    name: Deploy Reference Documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Initialize the workflow
        id: init
        uses: spetersenms/AL-Go/Actions/WorkflowInitialize@SchemaPath
        with:
          shell: powershell

      - name: Read settings
        uses: spetersenms/AL-Go/Actions/ReadSettings@SchemaPath
        with:
          shell: powershell

      - name: Determine Deployment Environments
        id: DetermineDeploymentEnvironments
        uses: spetersenms/AL-Go/Actions/DetermineDeploymentEnvironments@SchemaPath
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          getEnvironments: 'github-pages'
          type: 'Publish'

      - name: Setup Pages
        if: steps.DetermineDeploymentEnvironments.outputs.deployALDocArtifact == 1
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Build Reference Documentation
        uses: spetersenms/AL-Go/Actions/BuildReferenceDocumentation@SchemaPath
        with:
          shell: powershell
          artifacts: 'latest'

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ".aldoc/_site/"

      - name: Deploy to GitHub Pages
        if: steps.DetermineDeploymentEnvironments.outputs.deployALDocArtifact == 1
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

      - name: Finalize the workflow
        if: always()
        uses: spetersenms/AL-Go/Actions/WorkflowPostProcess@SchemaPath
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
